// <auto-generated />
using System;
using LoopLearner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoopLearner.Web.Server.Migrations
{
    [DbContext(typeof(LoopLearnerDbContext))]
    [Migration("20240905231502_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("LoopLearner.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3131eeb-ef3d-479f-818e-f3d211c29dfc"),
                            Email = "lincoln.abraham@example.com",
                            FirstName = "Abraham",
                            LastName = "Lincoln",
                            Password = "AQAAAAIAAYagAAAAEASLSjfD6irf5upaXl9r1o5R7HOIo6VjedgQxEg63sVIqV7VhJ7/SVyX7azBlU59JQ==",
                            UserName = "alincoln"
                        },
                        new
                        {
                            Id = new Guid("77a03a5c-cdcb-4f1f-afce-e4dc88b5832d"),
                            Email = "caesar.julius@example.com",
                            FirstName = "Julius",
                            LastName = "Caesar",
                            Password = "AQAAAAIAAYagAAAAELu7pJN9YHyLktJRvRur2L0kp+MHRsvRrXAnJiYjAHN1tLbdEcBTKZ6Zgdh2tD05EA==",
                            UserName = "jcaesar"
                        },
                        new
                        {
                            Id = new Guid("0d05e718-30f1-429e-af8a-21bcc20d7484"),
                            Email = "einstein.albert@example.com",
                            FirstName = "Albert",
                            LastName = "Einstein",
                            Password = "AQAAAAIAAYagAAAAEIlXdCfPlEGjk3dAGxq9BWM3CYWlIlLeXTI/RmqzYk4lVYBSivrHoEcgQpU2HiQOdw==",
                            UserName = "aeinstein"
                        },
                        new
                        {
                            Id = new Guid("fd918dab-5e99-4e62-8a54-85fb3a1cb609"),
                            Email = "curie.marie@example.com",
                            FirstName = "Marie",
                            LastName = "Curie",
                            Password = "AQAAAAIAAYagAAAAEI9sCXYpc5HM2z6LnR9IhauJjBia/vxRbVXhsFo7athp28FD33K1bzIqtre11T5ezg==",
                            UserName = "mcurie"
                        },
                        new
                        {
                            Id = new Guid("0e12a625-3b26-4928-98ae-cc37eeb552f1"),
                            Email = "davinci.leonardo@example.com",
                            FirstName = "Leonardo",
                            LastName = "da Vinci",
                            Password = "AQAAAAIAAYagAAAAEIn2SZW/exQ1mU6cN71kbmcRsCwurwiKfbWJYwODXkRmvNvyWfPS491C3Z8iubVh3Q==",
                            UserName = "ldavinci"
                        },
                        new
                        {
                            Id = new Guid("e4be5a33-3e9c-489f-b1d5-657cced38d60"),
                            Email = "shakespeare.william@example.com",
                            FirstName = "William",
                            LastName = "Shakespeare",
                            Password = "AQAAAAIAAYagAAAAEH6qF2ixPcfwrOxqsI7e60p32IPR7XtYW96HOWZapPIfVX21+HLimzdmyXOb0u7OZA==",
                            UserName = "wshakespeare"
                        },
                        new
                        {
                            Id = new Guid("bfedcc71-2bc5-43ce-9eb9-42c40d343ece"),
                            Email = "cleopatra@example.com",
                            FirstName = "Cleopatra",
                            LastName = "",
                            Password = "AQAAAAIAAYagAAAAED/OVJPyGLJr5dTYs7Rdmg28zTKX/bYKfRUtUfSGCP9Ml5SFOgAA375epOvxioShpA==",
                            UserName = "ccleopatra"
                        },
                        new
                        {
                            Id = new Guid("6492ee0e-88a6-4f4d-b60b-681e4982d736"),
                            Email = "alexander@example.com",
                            FirstName = "Alexander",
                            LastName = "the Great",
                            Password = "AQAAAAIAAYagAAAAEJ1dq5AxzM47r0JA9TEtANBOFl7ez+KKylz7YepVhWH7zv1SsDsXMSjRl5gJFZjaAQ==",
                            UserName = "aalexander"
                        },
                        new
                        {
                            Id = new Guid("f3bd68b1-dc3b-4157-bde4-c5f191d73f11"),
                            Email = "tesla.nikola@example.com",
                            FirstName = "Nikola",
                            LastName = "Tesla",
                            Password = "AQAAAAIAAYagAAAAEEse5wsM/GeLYa96j3X4KDS7McJjKyg+cMbvLfXuUEXd6xeXATYF7lLkX5przQQKTQ==",
                            UserName = "ntesla"
                        },
                        new
                        {
                            Id = new Guid("82d7c2a7-a411-425d-af93-6b03ac870f60"),
                            Email = "genghis.khan@example.com",
                            FirstName = "Genghis",
                            LastName = "Khan",
                            Password = "AQAAAAIAAYagAAAAEKit5WJksV+EgjWYTaELRjSUfJldUEb2jEfOdm51J4bXbVuRKzWYyTDCBXa0qrvLog==",
                            UserName = "wgenghis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
